added Corporate Identity css variables
marinus-g/Modules-Frontend pull request #2
Opened 2024-06-25 12:58 UTC by Bockkwurst

Ich habe drei background gradients hinzugefügt, da allgemein gesagt wurde, dass die bilder to much sind aber nur eine blank page auch nicht so gut ist. ansonsten habe ich für alle Farben, fonts und shapes (diesmal wirklich) einfache variablen erstellt.

2024-06-25 13:00 UTC, Bockkwurst commented
by the way: du hast noch merge ohne  review eingestellt. würde ich ändern.

2024-06-26 08:27 UTC, marinus-g requested changes

2024-06-26 08:27 UTC, marinus-g commented on src/utils/variables/variables.css
styles.css verwenden

2024-06-26 08:27 UTC, marinus-g commented on src/assets/shapes/shapes/wave-sand/wave-sand.svg
Zählt für alle assets: public folder benutzen

2024-06-26 08:29 UTC, marinus-g commented on src/assets/shapes/shapes/wave-sand/wave-sand.svg
nvm:
"Gibts keine Grundlegende Regelung. Musst nur sicher gehen das der Pfad in der angular.json unter architect.build.options.assets richtig eingetragen ist. Und Angular packt das default unter src/assets sollte aber bei jedem generierten Angular Projekt erstellt werden"

2024-07-05 07:35 UTC, merged